from unittest import TestCase
from ham.cw import Cw


class TestCw(TestCase):
    def setUp(self) -> None:
        self.morse = Cw()

    def test_Cw_Exists(self):
        self.assertIsInstance(self.morse, Cw)

    def test_letter_to_dot_dash(self):
        self.assertEqual(self.morse.letter_to_dot_dash("a"), ".-")
        self.assertEqual(self.morse.letter_to_dot_dash("b"), "-...")
        self.assertEqual(self.morse.letter_to_dot_dash("c"), "-.-.")
        self.assertEqual(self.morse.letter_to_dot_dash("d"), "-..")
        self.assertEqual(self.morse.letter_to_dot_dash("e"), ".")
        self.assertEqual(self.morse.letter_to_dot_dash("f"), "..-.")
        self.assertEqual(self.morse.letter_to_dot_dash("g"), "--.")
        self.assertEqual(self.morse.letter_to_dot_dash("h"), "....")
        self.assertEqual(self.morse.letter_to_dot_dash("i"), "..")
        self.assertEqual(self.morse.letter_to_dot_dash("j"), ".---")
        self.assertEqual(self.morse.letter_to_dot_dash("k"), "-.-")
        self.assertEqual(self.morse.letter_to_dot_dash("l"), ".-..")
        self.assertEqual(self.morse.letter_to_dot_dash("m"), "--")
        self.assertEqual(self.morse.letter_to_dot_dash("n"), "-.")
        self.assertEqual(self.morse.letter_to_dot_dash("o"), "---")
        self.assertEqual(self.morse.letter_to_dot_dash("p"), ".--.")
        self.assertEqual(self.morse.letter_to_dot_dash("q"), "--.-")
        self.assertEqual(self.morse.letter_to_dot_dash("r"), ".-.")
        self.assertEqual(self.morse.letter_to_dot_dash("s"), "...")
        self.assertEqual(self.morse.letter_to_dot_dash("t"), "-")
        self.assertEqual(self.morse.letter_to_dot_dash("u"), "..-")
        self.assertEqual(self.morse.letter_to_dot_dash("v"), "...-")
        self.assertEqual(self.morse.letter_to_dot_dash("w"), ".--")
        self.assertEqual(self.morse.letter_to_dot_dash("x"), "-..-")
        self.assertEqual(self.morse.letter_to_dot_dash("y"), "-.--")
        self.assertEqual(self.morse.letter_to_dot_dash("z"), "--..")
        self.assertEqual(self.morse.letter_to_dot_dash("A"), ".-")
        self.assertEqual(self.morse.letter_to_dot_dash("B"), "-...")
        self.assertEqual(self.morse.letter_to_dot_dash("C"), "-.-.")
        self.assertEqual(self.morse.letter_to_dot_dash("D"), "-..")
        self.assertEqual(self.morse.letter_to_dot_dash("E"), ".")
        self.assertEqual(self.morse.letter_to_dot_dash("F"), "..-.")
        self.assertEqual(self.morse.letter_to_dot_dash("G"), "--.")
        self.assertEqual(self.morse.letter_to_dot_dash("H"), "....")
        self.assertEqual(self.morse.letter_to_dot_dash("I"), "..")
        self.assertEqual(self.morse.letter_to_dot_dash("J"), ".---")
        self.assertEqual(self.morse.letter_to_dot_dash("K"), "-.-")
        self.assertEqual(self.morse.letter_to_dot_dash("L"), ".-..")
        self.assertEqual(self.morse.letter_to_dot_dash("M"), "--")
        self.assertEqual(self.morse.letter_to_dot_dash("N"), "-.")
        self.assertEqual(self.morse.letter_to_dot_dash("O"), "---")
        self.assertEqual(self.morse.letter_to_dot_dash("P"), ".--.")
        self.assertEqual(self.morse.letter_to_dot_dash("Q"), "--.-")
        self.assertEqual(self.morse.letter_to_dot_dash("R"), ".-.")
        self.assertEqual(self.morse.letter_to_dot_dash("S"), "...")
        self.assertEqual(self.morse.letter_to_dot_dash("T"), "-")
        self.assertEqual(self.morse.letter_to_dot_dash("U"), "..-")
        self.assertEqual(self.morse.letter_to_dot_dash("V"), "...-")
        self.assertEqual(self.morse.letter_to_dot_dash("W"), ".--")
        self.assertEqual(self.morse.letter_to_dot_dash("X"), "-..-")
        self.assertEqual(self.morse.letter_to_dot_dash("Y"), "-.--")
        self.assertEqual(self.morse.letter_to_dot_dash("Z"), "--..")
        self.assertEqual(self.morse.letter_to_dot_dash("0"), "-----")
        self.assertEqual(self.morse.letter_to_dot_dash("1"), ".----")
        self.assertEqual(self.morse.letter_to_dot_dash("2"), "..---")
        self.assertEqual(self.morse.letter_to_dot_dash("3"), "...--")
        self.assertEqual(self.morse.letter_to_dot_dash("4"), "....-")
        self.assertEqual(self.morse.letter_to_dot_dash("5"), ".....")
        self.assertEqual(self.morse.letter_to_dot_dash("6"), "-....")
        self.assertEqual(self.morse.letter_to_dot_dash("7"), "--...")
        self.assertEqual(self.morse.letter_to_dot_dash("8"), "---..")
        self.assertEqual(self.morse.letter_to_dot_dash("9"), "----.")

    def test_raises(self):
        self.assertRaises(ValueError, self.morse.letter_to_dot_dash, "±")
        self.assertRaises(ValueError, self.morse.letter_to_dot_dash, "§")
        self.assertRaises(ValueError, self.morse.letter_to_dot_dash, "`")

    def test_encode_morse(self):
        self.assertEqual(self.morse.encode_morse("a"), ". -_")
        self.assertEqual(self.morse.encode_morse("b"), "- . . ._")
        self.assertEqual(self.morse.encode_morse("c"), "- . - ._")
        self.assertEqual(self.morse.encode_morse("d"), "- . ._")
        self.assertEqual(self.morse.encode_morse("e"), "._")
        self.assertEqual(self.morse.encode_morse("f"), ". . - ._")
        self.assertEqual(self.morse.encode_morse("g"), "- - ._")
        self.assertEqual(self.morse.encode_morse("h"), ". . . ._")
        self.assertEqual(self.morse.encode_morse("i"), ". ._")
        self.assertEqual(self.morse.encode_morse("j"), ". - - -_")
        self.assertEqual(self.morse.encode_morse("k"), "- . -_")
        self.assertEqual(self.morse.encode_morse("l"), ". - . ._")
        self.assertEqual(self.morse.encode_morse("m"), "- -_")
        self.assertEqual(self.morse.encode_morse("n"), "- ._")
        self.assertEqual(self.morse.encode_morse("o"), "- - -_")
        self.assertEqual(self.morse.encode_morse("p"), ". - - ._")
        self.assertEqual(self.morse.encode_morse("q"), "- - . -_")
        self.assertEqual(self.morse.encode_morse("r"), ". - ._")
        self.assertEqual(self.morse.encode_morse("s"), ". . ._")
        self.assertEqual(self.morse.encode_morse("t"), "-_")
        self.assertEqual(self.morse.encode_morse("u"), ". . -_")
        self.assertEqual(self.morse.encode_morse("v"), ". . . -_")
        self.assertEqual(self.morse.encode_morse("w"), ". - -_")
        self.assertEqual(self.morse.encode_morse("x"), "- . . -_")
        self.assertEqual(self.morse.encode_morse("y"), "- . - -_")
        self.assertEqual(self.morse.encode_morse("z"), "- - . ._")
        self.assertEqual(self.morse.encode_morse("A"), ". -_")
        self.assertEqual(self.morse.encode_morse("B"), "- . . ._")
        self.assertEqual(self.morse.encode_morse("C"), "- . - ._")
        self.assertEqual(self.morse.encode_morse("D"), "- . ._")
        self.assertEqual(self.morse.encode_morse("E"), "._")
        self.assertEqual(self.morse.encode_morse("F"), ". . - ._")
        self.assertEqual(self.morse.encode_morse("G"), "- - ._")
        self.assertEqual(self.morse.encode_morse("H"), ". . . ._")
        self.assertEqual(self.morse.encode_morse("I"), ". ._")
        self.assertEqual(self.morse.encode_morse("J"), ". - - -_")
        self.assertEqual(self.morse.encode_morse("K"), "- . -_")
        self.assertEqual(self.morse.encode_morse("L"), ". - . ._")
        self.assertEqual(self.morse.encode_morse("M"), "- -_")
        self.assertEqual(self.morse.encode_morse("N"), "- ._")
        self.assertEqual(self.morse.encode_morse("O"), "- - -_")
        self.assertEqual(self.morse.encode_morse("P"), ". - - ._")
        self.assertEqual(self.morse.encode_morse("Q"), "- - . -_")
        self.assertEqual(self.morse.encode_morse("R"), ". - ._")
        self.assertEqual(self.morse.encode_morse("S"), ". . ._")
        self.assertEqual(self.morse.encode_morse("T"), "-_")
        self.assertEqual(self.morse.encode_morse("U"), ". . -_")
        self.assertEqual(self.morse.encode_morse("V"), ". . . -_")
        self.assertEqual(self.morse.encode_morse("W"), ". - -_")
        self.assertEqual(self.morse.encode_morse("X"), "- . . -_")
        self.assertEqual(self.morse.encode_morse("Y"), "- . - -_")
        self.assertEqual(self.morse.encode_morse("Z"), "- - . ._")
        self.assertEqual(self.morse.encode_morse("0"), "- - - - -_")
        self.assertEqual(self.morse.encode_morse("1"), ". - - - -_")
        self.assertEqual(self.morse.encode_morse("2"), ". . - - -_")
        self.assertEqual(self.morse.encode_morse("3"), ". . . - -_")
        self.assertEqual(self.morse.encode_morse("4"), ". . . . -_")
        self.assertEqual(self.morse.encode_morse("5"), ". . . . ._")
        self.assertEqual(self.morse.encode_morse("6"), "- . . . ._")
        self.assertEqual(self.morse.encode_morse("7"), "- - . . ._")
        self.assertEqual(self.morse.encode_morse("8"), "- - - . ._")
        self.assertEqual(self.morse.encode_morse("9"), "- - - - ._")


    def test_encode_paris(self):
        self.assertEqual(self.morse.encode_morse("paris"), ". - - . . - . - . . . . . ._")

    def test_len_dits(self):
        # Paris should be 50 dits in length
        self.assertEqual(50, 50)

    def test_len_chr(self):
        self.assertEqual(self.morse.len_chr("p"), 8)
        self.assertEqual(self.morse.len_chr("a"), 4)
        self.assertEqual(self.morse.len_chr("r"), 5)
        self.assertEqual(self.morse.len_chr("i"), 2)
        self.assertEqual(self.morse.len_chr("s"), 3)

    def test_len_dits(self):
        self.assertEqual(self.morse.len_dits(self.morse.encode_morse("paris")), 42)
