from unittest import TestCase
from ham.cw import Cw


class TestCw(TestCase):
    def setUp(self) -> None:
        self.morse = Cw()

    def test_Cw_Exists(self):
        self.assertIsInstance(self.morse, Cw)

    def test_letter_to_dot_dash(self):
        self.assertEqual(self.morse.letter_to_dot_dash("a"), ".-")
        self.assertEqual(self.morse.letter_to_dot_dash("b"), "-...")
        self.assertEqual(self.morse.letter_to_dot_dash("c"), "-.-.")
        self.assertEqual(self.morse.letter_to_dot_dash("d"), "-..")
        self.assertEqual(self.morse.letter_to_dot_dash("e"), ".")
        self.assertEqual(self.morse.letter_to_dot_dash("f"), "..-.")
        self.assertEqual(self.morse.letter_to_dot_dash("g"), "--.")
        self.assertEqual(self.morse.letter_to_dot_dash("h"), "....")
        self.assertEqual(self.morse.letter_to_dot_dash("i"), "..")
        self.assertEqual(self.morse.letter_to_dot_dash("j"), ".---")
        self.assertEqual(self.morse.letter_to_dot_dash("k"), "-.-")
        self.assertEqual(self.morse.letter_to_dot_dash("l"), ".-..")
        self.assertEqual(self.morse.letter_to_dot_dash("m"), "--")
        self.assertEqual(self.morse.letter_to_dot_dash("n"), "-.")
        self.assertEqual(self.morse.letter_to_dot_dash("o"), "---")
        self.assertEqual(self.morse.letter_to_dot_dash("p"), ".--.")
        self.assertEqual(self.morse.letter_to_dot_dash("q"), "--.-")
        self.assertEqual(self.morse.letter_to_dot_dash("r"), ".-.")
        self.assertEqual(self.morse.letter_to_dot_dash("s"), "...")
        self.assertEqual(self.morse.letter_to_dot_dash("t"), "-")
        self.assertEqual(self.morse.letter_to_dot_dash("u"), "..-")
        self.assertEqual(self.morse.letter_to_dot_dash("v"), "...-")
        self.assertEqual(self.morse.letter_to_dot_dash("w"), ".--")
        self.assertEqual(self.morse.letter_to_dot_dash("x"), "-..-")
        self.assertEqual(self.morse.letter_to_dot_dash("y"), "-.--")
        self.assertEqual(self.morse.letter_to_dot_dash("z"), "--..")
        self.assertEqual(self.morse.letter_to_dot_dash("A"), ".-")
        self.assertEqual(self.morse.letter_to_dot_dash("B"), "-...")
        self.assertEqual(self.morse.letter_to_dot_dash("C"), "-.-.")
        self.assertEqual(self.morse.letter_to_dot_dash("D"), "-..")
        self.assertEqual(self.morse.letter_to_dot_dash("E"), ".")
        self.assertEqual(self.morse.letter_to_dot_dash("F"), "..-.")
        self.assertEqual(self.morse.letter_to_dot_dash("G"), "--.")
        self.assertEqual(self.morse.letter_to_dot_dash("H"), "....")
        self.assertEqual(self.morse.letter_to_dot_dash("I"), "..")
        self.assertEqual(self.morse.letter_to_dot_dash("J"), ".---")
        self.assertEqual(self.morse.letter_to_dot_dash("K"), "-.-")
        self.assertEqual(self.morse.letter_to_dot_dash("L"), ".-..")
        self.assertEqual(self.morse.letter_to_dot_dash("M"), "--")
        self.assertEqual(self.morse.letter_to_dot_dash("N"), "-.")
        self.assertEqual(self.morse.letter_to_dot_dash("O"), "---")
        self.assertEqual(self.morse.letter_to_dot_dash("P"), ".--.")
        self.assertEqual(self.morse.letter_to_dot_dash("Q"), "--.-")
        self.assertEqual(self.morse.letter_to_dot_dash("R"), ".-.")
        self.assertEqual(self.morse.letter_to_dot_dash("S"), "...")
        self.assertEqual(self.morse.letter_to_dot_dash("T"), "-")
        self.assertEqual(self.morse.letter_to_dot_dash("U"), "..-")
        self.assertEqual(self.morse.letter_to_dot_dash("V"), "...-")
        self.assertEqual(self.morse.letter_to_dot_dash("W"), ".--")
        self.assertEqual(self.morse.letter_to_dot_dash("X"), "-..-")
        self.assertEqual(self.morse.letter_to_dot_dash("Y"), "-.--")
        self.assertEqual(self.morse.letter_to_dot_dash("Z"), "--..")
        self.assertEqual(self.morse.letter_to_dot_dash("0"), "-----")
        self.assertEqual(self.morse.letter_to_dot_dash("1"), ".----")
        self.assertEqual(self.morse.letter_to_dot_dash("2"), "..---")
        self.assertEqual(self.morse.letter_to_dot_dash("3"), "...--")
        self.assertEqual(self.morse.letter_to_dot_dash("4"), "....-")
        self.assertEqual(self.morse.letter_to_dot_dash("5"), ".....")
        self.assertEqual(self.morse.letter_to_dot_dash("6"), "-....")
        self.assertEqual(self.morse.letter_to_dot_dash("7"), "--...")
        self.assertEqual(self.morse.letter_to_dot_dash("8"), "---..")
        self.assertEqual(self.morse.letter_to_dot_dash("9"), "----.")

    def test_raises(self):
        self.assertRaises(ValueError, self.morse.letter_to_dot_dash, "±")
        self.assertRaises(ValueError, self.morse.letter_to_dot_dash, "§")
        self.assertRaises(ValueError, self.morse.letter_to_dot_dash, "`")

    def test_cw_timing(self):
        self.assertEqual(self.morse.cw_timing("a"), ". -_")
        self.assertEqual(self.morse.cw_timing("b"), "- . . ._")
        self.assertEqual(self.morse.cw_timing("c"), "- . - ._")
        self.assertEqual(self.morse.cw_timing("d"), "- . ._")
        self.assertEqual(self.morse.cw_timing("e"), "._")
        self.assertEqual(self.morse.cw_timing("f"), ". . - ._")
        self.assertEqual(self.morse.cw_timing("g"), "- - ._")
        self.assertEqual(self.morse.cw_timing("h"), ". . . ._")
        self.assertEqual(self.morse.cw_timing("i"), ". ._")
        self.assertEqual(self.morse.cw_timing("j"), ". - - -_")
        self.assertEqual(self.morse.cw_timing("k"), "- . -_")
        self.assertEqual(self.morse.cw_timing("l"), ". - . ._")
        self.assertEqual(self.morse.cw_timing("m"), "- -_")
        self.assertEqual(self.morse.cw_timing("n"), "- ._")
        self.assertEqual(self.morse.cw_timing("o"), "- - -_")
        self.assertEqual(self.morse.cw_timing("p"), ". - - ._")
        self.assertEqual(self.morse.cw_timing("q"), "- - . -_")
        self.assertEqual(self.morse.cw_timing("r"), ". - ._")
        self.assertEqual(self.morse.cw_timing("s"), ". . ._")
        self.assertEqual(self.morse.cw_timing("t"), "-_")
        self.assertEqual(self.morse.cw_timing("u"), ". . -_")
        self.assertEqual(self.morse.cw_timing("v"), ". . . -_")
        self.assertEqual(self.morse.cw_timing("w"), ". - -_")
        self.assertEqual(self.morse.cw_timing("x"), "- . . -_")
        self.assertEqual(self.morse.cw_timing("y"), "- . - -_")
        self.assertEqual(self.morse.cw_timing("z"), "- - . ._")
        self.assertEqual(self.morse.cw_timing("A"), ". -_")
        self.assertEqual(self.morse.cw_timing("B"), "- . . ._")
        self.assertEqual(self.morse.cw_timing("C"), "- . - ._")
        self.assertEqual(self.morse.cw_timing("D"), "- . ._")
        self.assertEqual(self.morse.cw_timing("E"), "._")
        self.assertEqual(self.morse.cw_timing("F"), ". . - ._")
        self.assertEqual(self.morse.cw_timing("G"), "- - ._")
        self.assertEqual(self.morse.cw_timing("H"), ". . . ._")
        self.assertEqual(self.morse.cw_timing("I"), ". ._")
        self.assertEqual(self.morse.cw_timing("J"), ". - - -_")
        self.assertEqual(self.morse.cw_timing("K"), "- . -_")
        self.assertEqual(self.morse.cw_timing("L"), ". - . ._")
        self.assertEqual(self.morse.cw_timing("M"), "- -_")
        self.assertEqual(self.morse.cw_timing("N"), "- ._")
        self.assertEqual(self.morse.cw_timing("O"), "- - -_")
        self.assertEqual(self.morse.cw_timing("P"), ". - - ._")
        self.assertEqual(self.morse.cw_timing("Q"), "- - . -_")
        self.assertEqual(self.morse.cw_timing("R"), ". - ._")
        self.assertEqual(self.morse.cw_timing("S"), ". . ._")
        self.assertEqual(self.morse.cw_timing("T"), "-_")
        self.assertEqual(self.morse.cw_timing("U"), ". . -_")
        self.assertEqual(self.morse.cw_timing("V"), ". . . -_")
        self.assertEqual(self.morse.cw_timing("W"), ". - -_")
        self.assertEqual(self.morse.cw_timing("X"), "- . . -_")
        self.assertEqual(self.morse.cw_timing("Y"), "- . - -_")
        self.assertEqual(self.morse.cw_timing("Z"), "- - . ._")
        self.assertEqual(self.morse.cw_timing("0"), "- - - - -_")
        self.assertEqual(self.morse.cw_timing("1"), ". - - - -_")
        self.assertEqual(self.morse.cw_timing("2"), ". . - - -_")
        self.assertEqual(self.morse.cw_timing("3"), ". . . - -_")
        self.assertEqual(self.morse.cw_timing("4"), ". . . . -_")
        self.assertEqual(self.morse.cw_timing("5"), ". . . . ._")
        self.assertEqual(self.morse.cw_timing("6"), "- . . . ._")
        self.assertEqual(self.morse.cw_timing("7"), "- - . . ._")
        self.assertEqual(self.morse.cw_timing("8"), "- - - . ._")
        self.assertEqual(self.morse.cw_timing("9"), "- - - - ._")


    def test_encode_paris(self):
        self.assertEqual(self.morse.cw_timing("paris"), ". - - . . - . - . . . . . ._")

    def test_len_dits(self):
        # Paris should be 50 dits in length
        self.assertEqual(50, 50)

    def test_len_chr(self):
        self.assertEqual(self.morse.len_chr("p"), 8)
        self.assertEqual(self.morse.len_chr("a"), 4)
        self.assertEqual(self.morse.len_chr("r"), 5)
        self.assertEqual(self.morse.len_chr("i"), 2)
        self.assertEqual(self.morse.len_chr("s"), 3)

    def test_len_dits(self):
        self.assertEqual(self.morse.len_dits(self.morse.cw_timing("paris")), 42)
