from unittest import TestCase
from ham.cw import Cw


class TestCw(TestCase):
    def setUp(self) -> None:
        self.cw = Cw()

    def test_class_exists(self):
        self.assertIsInstance(self.cw, Cw)

    def test_letter_to_dot_dash(self):
        self.assertEqual(self.cw.letter_to_dot_dash("a"), ".-")
        self.assertEqual(self.cw.letter_to_dot_dash("b"), "-...")
        self.assertEqual(self.cw.letter_to_dot_dash("c"), "-.-.")
        self.assertEqual(self.cw.letter_to_dot_dash("d"), "-..")
        self.assertEqual(self.cw.letter_to_dot_dash("e"), ".")
        self.assertEqual(self.cw.letter_to_dot_dash("f"), "..-.")
        self.assertEqual(self.cw.letter_to_dot_dash("g"), "--.")
        self.assertEqual(self.cw.letter_to_dot_dash("h"), "....")
        self.assertEqual(self.cw.letter_to_dot_dash("i"), "..")
        self.assertEqual(self.cw.letter_to_dot_dash("j"), ".---")
        self.assertEqual(self.cw.letter_to_dot_dash("k"), "-.-")
        self.assertEqual(self.cw.letter_to_dot_dash("l"), ".-..")
        self.assertEqual(self.cw.letter_to_dot_dash("m"), "--")
        self.assertEqual(self.cw.letter_to_dot_dash("n"), "-.")
        self.assertEqual(self.cw.letter_to_dot_dash("o"), "---")
        self.assertEqual(self.cw.letter_to_dot_dash("p"), ".--.")
        self.assertEqual(self.cw.letter_to_dot_dash("q"), "--.-")
        self.assertEqual(self.cw.letter_to_dot_dash("r"), ".-.")
        self.assertEqual(self.cw.letter_to_dot_dash("s"), "...")
        self.assertEqual(self.cw.letter_to_dot_dash("t"), "-")
        self.assertEqual(self.cw.letter_to_dot_dash("u"), "..-")
        self.assertEqual(self.cw.letter_to_dot_dash("v"), "...-")
        self.assertEqual(self.cw.letter_to_dot_dash("w"), ".--")
        self.assertEqual(self.cw.letter_to_dot_dash("x"), "-..-")
        self.assertEqual(self.cw.letter_to_dot_dash("y"), "-.--")
        self.assertEqual(self.cw.letter_to_dot_dash("z"), "--..")
        self.assertEqual(self.cw.letter_to_dot_dash("A"), ".-")
        self.assertEqual(self.cw.letter_to_dot_dash("B"), "-...")
        self.assertEqual(self.cw.letter_to_dot_dash("C"), "-.-.")
        self.assertEqual(self.cw.letter_to_dot_dash("D"), "-..")
        self.assertEqual(self.cw.letter_to_dot_dash("E"), ".")
        self.assertEqual(self.cw.letter_to_dot_dash("F"), "..-.")
        self.assertEqual(self.cw.letter_to_dot_dash("G"), "--.")
        self.assertEqual(self.cw.letter_to_dot_dash("H"), "....")
        self.assertEqual(self.cw.letter_to_dot_dash("I"), "..")
        self.assertEqual(self.cw.letter_to_dot_dash("J"), ".---")
        self.assertEqual(self.cw.letter_to_dot_dash("K"), "-.-")
        self.assertEqual(self.cw.letter_to_dot_dash("L"), ".-..")
        self.assertEqual(self.cw.letter_to_dot_dash("M"), "--")
        self.assertEqual(self.cw.letter_to_dot_dash("N"), "-.")
        self.assertEqual(self.cw.letter_to_dot_dash("O"), "---")
        self.assertEqual(self.cw.letter_to_dot_dash("P"), ".--.")
        self.assertEqual(self.cw.letter_to_dot_dash("Q"), "--.-")
        self.assertEqual(self.cw.letter_to_dot_dash("R"), ".-.")
        self.assertEqual(self.cw.letter_to_dot_dash("S"), "...")
        self.assertEqual(self.cw.letter_to_dot_dash("T"), "-")
        self.assertEqual(self.cw.letter_to_dot_dash("U"), "..-")
        self.assertEqual(self.cw.letter_to_dot_dash("V"), "...-")
        self.assertEqual(self.cw.letter_to_dot_dash("W"), ".--")
        self.assertEqual(self.cw.letter_to_dot_dash("X"), "-..-")
        self.assertEqual(self.cw.letter_to_dot_dash("Y"), "-.--")
        self.assertEqual(self.cw.letter_to_dot_dash("Z"), "--..")
        self.assertEqual(self.cw.letter_to_dot_dash("0"), "-----")
        self.assertEqual(self.cw.letter_to_dot_dash("1"), ".----")
        self.assertEqual(self.cw.letter_to_dot_dash("2"), "..---")
        self.assertEqual(self.cw.letter_to_dot_dash("3"), "...--")
        self.assertEqual(self.cw.letter_to_dot_dash("4"), "....-")
        self.assertEqual(self.cw.letter_to_dot_dash("5"), ".....")
        self.assertEqual(self.cw.letter_to_dot_dash("6"), "-....")
        self.assertEqual(self.cw.letter_to_dot_dash("7"), "--...")
        self.assertEqual(self.cw.letter_to_dot_dash("8"), "---..")
        self.assertEqual(self.cw.letter_to_dot_dash("9"), "----.")

    def test_raises(self):
        self.assertRaises(ValueError, self.cw.letter_to_dot_dash, "±")
        self.assertRaises(ValueError, self.cw.letter_to_dot_dash, "§")
        self.assertRaises(ValueError, self.cw.letter_to_dot_dash, "`")

